/* -------------------------------------------------------------------------- */
/*               Feel free to add/replace these silly team names              */
/* -------------------------------------------------------------------------- */

export const teamNames: string[] = [
    "Async Avengers",
    "CSS Wizards",
    "Code Conquerors",
    "HTML Heroes",
    "JavaScript Ninjas",
    "DOM Dynamos",
    "Debug Divas",
    "Agile Alchemists",
    "Git Gurus",
    "JSON Juggernauts",
    "Callback Commandos",
    "Responsive Renegades",
    "Pixel Pioneers",
    "Event Loop Experts",
    "Frontend Force",
    "Code Crafters",
    "Semantic Sages",
    "Module Masters",
    "Function Fanatics",
    "API Aces",
    "Closure Crusaders",
    "Full-Stack Falcons",
    "RESTful Rebels",
    "Tag Titans",
    "Syntax Sorcerers",
    "Variable Vikings",
    "Script Samurai",
    "UI Unicorns",
    "Web Warriors",
    "Object Oriented Operatives",
    "Flexbox Fanatics",
    "Async Architects",
    "Promise Pioneers",
    "Code Catalysts",
    "Express Enthusiasts",
    "Node Nomads",
    "React Rulers",
    "Design Pattern Dynamos",
    "Component Commanders",
    "SASS Soldiers",
    "Conditional Crushers",
    "Algorithm Aficionados",
    "Grid Gurus",
    "Element Experts",
    "Prototype Pioneers",
    "Hoisting Heroes",
    "Axios Action Heroes",
    "Immutable Invincibles",
    "Event Emperors",
    "Function Furies",
  ];
  